stages:
  - deploy

.docker_runner_config: &docker_runner_config
  tags:
    - docker-runner

pages:
  stage: deploy
  image: node:14.5.0-alpine
  <<: *docker_runner_config
  script:
    - yarn install --frozen-lockfile
    - yarn build
    - rm -rf public && mv build public
  only:
    - master
  artifacts:
    paths:
      - public
    expire_in: 1 day
